version: '3.9'

services:
  server:
    image: reeeeegis/youtube-clone-nodejs-api-backend:latest
    ports:
      - 3001:3001
    volumes:
      - uploads:/uploads
    env_file:
      - ./config/.env
  frontend:
    image: reeeeegis/youtube-clone-vue-nodejs-frontend:latest
    ports:
      - 8080:8080
    env_file:
        - .env.development.local
    volumes:
      - /app/node_modules
    depends_on:
      - server
    networks:
      - youtube

volumes:
  uploads:
networks:
  youtube: